---
title: "session3"
author: "Kevin Wang and Garth Tarr"
date: "05/11/2019"
output:
  html_document:
    css: style.css
---



# Learning outcomes of this session

+ More plotting with `ggplot2`
+ `for` loops and `purrr::map` functions
+ Modelling with `broom`



# Loading packages

```{r}
library(tidyverse)
library(skimr)
```


# Loading cleaned sample data

```{r}
session3_data = read_csv(file = "data/session3_data.csv") %>% 
  dplyr::select(-time, -dose)

clean_data = session3_data %>% 
  dplyr::mutate_if(is.numeric, .funs = log)

hw_data = clean_data %>% 
  dplyr::filter(strain == "HW")

le_data = clean_data %>% 
  dplyr::filter(strain == "LE")
```


# t-test

```{r}
t.test(x = hw_data$Ahrr, 
       y = le_data$Ahrr)

t.test(x = hw_data$Cxcr7, 
       y = le_data$Cxcr7)

t.test(Ahrr ~ strain, data = clean_data)
```




```{r}
gene_long = clean_data %>%
  tidyr::pivot_longer(
    cols = -c("strain", "sample"),
    names_to = "gene_symbols",
    values_to = "gene_expression")


gene_long


gene_nest = gene_long %>% 
  group_by(gene_symbols) %>% 
  tidyr::nest()

gene_nest

gene_nest$data[1:2]

t_test_ge = function(this_data){
  t.test(gene_expression ~ strain, data = this_data)
}


gene_test = gene_nest %>% 
  dplyr::mutate(test = purrr::map(.x = data, 
                                  .f = t_test_ge),
                test_tidy = purrr::map(.x = test,
                                       .f = broom::tidy))



gene_model_long = gene_test %>% 
  tidyr::unnest(test_tidy)


gene_model_long %>% 
  ggplot(aes(x = p.value)) +
  geom_histogram()


gene_model_long %>% 
  dplyr::filter(p.value < 0.0001) %>% 
  tidyr::unnest(data) %>% 
  dplyr::mutate(
    label = paste0(gene_symbols, 
                   ", p-value = ", 
                   signif(p.value, 2))) %>% 
  ggplot(aes(x = strain, 
             y = gene_expression)) +
  geom_boxplot() +
  facet_wrap(~ label, scales = "free")
```


















# Regression analysis

```{r}
clean_data %>% 
  ggplot(aes(x = Ahrr,
             y = Cxcr7,
             colour = strain)) +
  geom_point() +
  geom_smooth(method = "lm")


lm(Cxcr7 ~ Ahrr, data = clean_data)
lm(Cxcr7 ~ Ahrr, data = hw_data)
lm(Cxcr7 ~ Ahrr, data = le_data)

lm_Cxcr7_Ahrr = function(this_data){
  lm(Cxcr7 ~ Ahrr, data = this_data)
}

list_data = list(
  clean_data = clean_data, 
  hw_data = hw_data,
  le_data = le_data)

purrr::map(.x = list_data, 
           .f = lm_Cxcr7_Ahrr)

purrr::map(.x = list_data, 
           .f = lm_Cxcr7_Ahrr) %>% 
  purrr::map(.f = broom::tidy)
```




```{r}
gene_long = clean_data %>%
  tidyr::pivot_longer(
    cols = -c("strain", "Cxcr7", "sample"),
    names_to = "gene_symbols",
    values_to = "gene_expression")

gene_long

gene_nest = gene_long %>% 
  group_by(strain, gene_symbols) %>% 
  tidyr::nest()

gene_nest$data[1:2]

lm_Cxcr7_ge = function(this_data){
  lm(Cxcr7 ~ gene_expression, data = this_data)
}

gene_model = gene_nest %>% 
  dplyr::mutate(lm_obj = purrr::map(.x = data, 
                                    .f = lm_Cxcr7_ge),
                lm_tidy = purrr::map(.x = lm_obj,
                                     .f = broom::tidy))



gene_model_long = gene_model %>% 
  dplyr::select(-data, -lm_obj) %>% 
  tidyr::unnest(lm_tidy) %>% 
  dplyr::select(strain, gene_symbols, term, estimate) %>% 
  dplyr::filter(term == "gene_expression")


gene_model_long


gene_model_wide = gene_model_long %>% 
  dplyr::ungroup() %>% 
  tidyr::pivot_wider(names_from = "strain",
                     values_from = "estimate")


gene_model_wide %>% 
  ggplot(aes(x = HW, y = LE)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, colour = "red")

gene_model_wide %>% 
  ggplot(aes(x = HW, y = LE,
             label = gene_symbols)) +
  geom_text() +
  geom_abline(slope = 1, intercept = 0, colour = "red")
```

# Session Info
```{r}
sessionInfo()
```

